version: '3.8'

services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins
    ports:
    - "50000:50000"
    - "9080:8080"
    volumes:
      - ./jenkins_home:/var/jenkins_home
    restart: always