version: '3.8'

services:
  docker:
    image: docker:dind
    container_name: jenkins-docker
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR: /certs
    volumes:
      - ./jenkins-certs:/certs/client
      - ./jenkins-data:/var/jenkins_home
    networks:
      - jenkins
    expose:
      - "2376"

  jenkins:
    build: .
    container_name: jenkins
    privileged: true
    environment:
      DOCKER_HOST: tcp://docker:2376
      DOCKER_CERT_PATH: /certs/client
      DOCKER_TLS_VERIFY: 1
    volumes:
      - ./jenkins-data:/var/jenkins_home
      - ./jenkins-certs:/certs/client:ro
    ports:
      - "9090:8080"
      - "50000:50000"
    networks:
      - jenkins
    depends_on:
      - docker
    restart: on-failure

networks:
  jenkins:

volumes:
  jenkins-data:
  jenkins-certs: